# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Spectral decomposition of a symetric matrix
#'
#' Eigen decomposition of dense symmetric/hermitian matrix M
#' using standard or divide-and-conquer methods.
#' the divide-and-conquer method provides slightly different results
#' than the standard method, but is considerably faster for large matrices
#'
#' @param M a matrix.
#' //@param method "dc" indicates divide-and-conquer method (par).
#' //              "std" indicates standard method.
#' @export eigendec
eigendec <- function(M) {
    .Call('_gasper_eigendec', PACKAGE = 'gasper', M)
}

#' Matrix multiplication
#'
#' @param A a matrix.
#' @param B a matrix.
#' @export matmult
matmult <- function(A, B) {
    .Call('_gasper_matmult', PACKAGE = 'gasper', A, B)
}

